# data_management/performance_tracker_v2_5.py
"""
Manages the persistent storage and retrieval of performance data related to
EOTS v2.5's signals and recommendations, facilitating the system's learning loop.

This module interacts with database_manager_v2_5.py for database operations.
"""
import logging
import json
import pandas as pd
from typing import List, Dict, Any, Optional, Union
from datetime import datetime, timedelta 

# --- Relative import for database_manager ---
# Since database_manager.py is now in the SAME data_management/ package,
# we use a relative import.
from . import database_manager_v2_5 as db_manager
# If you prefer to import specific functions from database_manager:
# from .database_manager_v2_5 import get_db_connection, store_trade_recommendation_pg, etc.

# If psycopg2 types are used for type hinting and it's available in the db_manager context
try:
    import psycopg2.extras # For type hinting DictCursor if used in db_manager
except ImportError:
    psycopg2 = None # type: ignore

# --- Module-Specific Logger ---
logger = logging.getLogger(__name__)
# (Your existing logger setup can follow if you prefer it here,
# otherwise, main runner script should handle root logger config)

class PerformanceTrackerV2_5:
    """
    Handles logging and retrieval of trade recommendation performance data.
    """
    def __init__(self, db_connection_details: Dict[str, str]):
        """
        Initializes the PerformanceTrackerV2_5.

        Args:
            db_connection_details (Dict[str, str]): Credentials for DB connection.
        """
        self.db_connection_details = db_connection_details
        conn_test = None
        try:
            conn_test = db_manager.get_db_connection(self.db_connection_details)
            if conn_test:
                logger.info("PerformanceTrackerV2_5: Database connection details validated successfully.")
            else:
                logger.error("PerformanceTrackerV2_5: Failed to establish a test database connection.")
        except Exception as e:
            logger.error(f"PerformanceTrackerV2_5: Error during initial DB connection test: {e}", exc_info=True)
        finally:
            if conn_test:
                conn_test.close()

    def _execute_query(self, query: str, params: Optional[tuple] = None, fetch_one: bool = False, fetch_all: bool = False, commit: bool = False) -> Any:
        """
        Helper function to execute database queries.
        Manages connection opening and closing for each operation.
        """
        conn = None
        results = None
        try:
            conn = db_manager.get_db_connection(self.db_connection_details)
            if not conn:
                logger.error("PerformanceTrackerV2_5: Failed to get database connection for query execution.")
                return None
            
            # Use DictCursor if psycopg2 is available and imported in db_manager
            cursor_factory_to_use = None
            if psycopg2 and hasattr(psycopg2, 'extras') and hasattr(psycopg2.extras, 'DictCursor'):
                 cursor_factory_to_use = psycopg2.extras.DictCursor

            with conn.cursor(cursor_factory=cursor_factory_to_use) as cur:
                cur.execute(query, params)
                if fetch_one:
                    results = cur.fetchone()
                elif fetch_all:
                    results = cur.fetchall()
                
                if commit:
                    conn.commit()
                    logger.debug(f"Query executed and committed: {query[:100]}...")
                else:
                    logger.debug(f"Query executed: {query[:100]}...")
        except Exception as e:
            logger.error(f"PerformanceTrackerV2_5: Database query error: {e}\nQuery: {query}\nParams: {params}", exc_info=True)
            if conn:
                conn.rollback()
        finally:
            if conn:
                conn.close()
        return results

    def log_atif_recommendation(self, recommendation_payload: Dict[str, Any]) -> Optional[str]:
        """
        Logs a new trade recommendation generated by the ATIF.
        """
        if not isinstance(recommendation_payload, dict):
            logger.error("PerformanceTrackerV2_5: Invalid recommendation_payload (not a dict). Cannot log.")
            return None

        rec_id = recommendation_payload.get('recommendation_id')
        if not rec_id:
            logger.error("PerformanceTrackerV2_5: recommendation_id missing in payload. Cannot log.")
            return None
        
        json_fields = ['ticker_context_at_issuance_json', 'triggering_signals_json', 'atif_situational_assessment_json', 'selected_contracts_json', 'parameters_detail_json']
        for field in json_fields:
            if field in recommendation_payload and recommendation_payload[field] is not None and not isinstance(recommendation_payload[field], str):
                try:
                    recommendation_payload[field] = json.dumps(recommendation_payload[field])
                except TypeError as e_json:
                    logger.warning(f"PerformanceTrackerV2_5: Could not serialize field '{field}' to JSON for rec ID {rec_id}. Setting to null. Error: {e_json}")
                    recommendation_payload[field] = None
            elif field in recommendation_payload and recommendation_payload[field] is None:
                 recommendation_payload[field] = None # Keep it None if it was None

        conn = None
        try:
            conn = db_manager.get_db_connection(self.db_connection_details)
            if conn:
                success = db_manager.store_trade_recommendation_pg(conn, [recommendation_payload])
                if success:
                    logger.info(f"PerformanceTrackerV2_5: Successfully logged ATIF recommendation ID: {rec_id}")
                    return rec_id
                else:
                    logger.error(f"PerformanceTrackerV2_5: Failed to log ATIF recommendation ID: {rec_id} (db_manager returned False).")
                    return None
            else:
                logger.error(f"PerformanceTrackerV2_5: Failed to get DB connection for logging recommendation {rec_id}.")
                return None
        except Exception as e:
            logger.error(f"PerformanceTrackerV2_5: Error logging ATIF recommendation ID {rec_id}: {e}", exc_info=True)
            return None
        finally:
            if conn:
                conn.close()

    def log_trade_outcome(self, outcome_payload: Dict[str, Any]) -> Optional[int]:
        """
        Logs the outcome of a closed trade.
        """
        if not isinstance(outcome_payload, dict):
            logger.error("PerformanceTrackerV2_5: Invalid outcome_payload (not a dict). Cannot log.")
            return None

        rec_id = outcome_payload.get('recommendation_id')
        if not rec_id:
            logger.error("PerformanceTrackerV2_5: recommendation_id missing in outcome payload. Cannot log.")
            return None

        json_fields_outcome = ['contracts_traded_json', 'metrics_at_entry_json', 'metrics_at_exit_json', 'notes_json']
        for field in json_fields_outcome:
            if field in outcome_payload and outcome_payload[field] is not None and not isinstance(outcome_payload[field], str):
                try:
                    outcome_payload[field] = json.dumps(outcome_payload[field])
                except TypeError as e_json_outcome:
                    logger.warning(f"PerformanceTrackerV2_5: Could not serialize field '{field}' to JSON for outcome of rec ID {rec_id}. Setting to null. Error: {e_json_outcome}")
                    outcome_payload[field] = None
            elif field in outcome_payload and outcome_payload[field] is None:
                outcome_payload[field] = None


        conn = None
        try:
            conn = db_manager.get_db_connection(self.db_connection_details)
            if conn:
                trade_log_ids = db_manager.store_trade_outcome_pg(conn, [outcome_payload])
                if trade_log_ids and trade_log_ids[0] is not None:
                    trade_log_id = trade_log_ids[0]
                    logger.info(f"PerformanceTrackerV2_5: Successfully logged trade outcome for rec ID {rec_id}. Trade Log ID: {trade_log_id}")
                    return trade_log_id
                else:
                    logger.error(f"PerformanceTrackerV2_5: Failed to log trade outcome for rec ID {rec_id} (db_manager returned no ID).")
                    return None
            else:
                logger.error(f"PerformanceTrackerV2_5: Failed to get DB connection for logging outcome for rec ID {rec_id}.")
                return None
        except Exception as e:
            logger.error(f"PerformanceTrackerV2_5: Error logging trade outcome for rec ID {rec_id}: {e}", exc_info=True)
            return None
        finally:
            if conn:
                conn.close()

    def _safe_json_load(self, json_str: Optional[str], default_val: Any = None) -> Any:
        """Safely loads a JSON string, returning a default value on error or if input is None."""
        if json_str is None:
            return default_val
        try:
            return json.loads(json_str)
        except (json.JSONDecodeError, TypeError):
            return default_val if default_val is not None else {}


    def _extract_primary_signal_type(self, signals_json_str: Optional[str]) -> str:
        """
        Extracts a primary signal type from the triggering_signals_json.
        This is a simplified example; real logic might be more complex.
        """
        signals_data = self._safe_json_load(signals_json_str, [])
        if isinstance(signals_data, list) and signals_data:
            # Example: take the type of the first signal, or a specific key
            first_signal = signals_data[0]
            if isinstance(first_signal, dict) and 'type' in first_signal:
                return str(first_signal['type'])
        return "UnknownSignal"

    def get_historical_performance_for_setups(
        self,
        symbol: str,
        lookback_days: int = 90,
        min_trades_for_stats: int = 5,
        # Filters are now more flexible, allowing for partial matches or specific key-value checks
        signal_filters: Optional[List[Dict[str, Any]]] = None, # e.g., [{"key_path": "type", "value": "MSPI_Bull", "match_type": "exact"}]
        regime_filters: Optional[List[str]] = None,
        context_filters: Optional[List[Dict[str, Any]]] = None, # e.g., [{"key_path": "is_0DTE", "value": True, "match_type": "exact"}]
        strategy_type_filters: Optional[List[str]] = None
    ) -> pd.DataFrame:
        perf_logger = logger.getChild("GetHistoricalPerformance")
        perf_logger.info(f"Fetching historical performance for {symbol}, lookback {lookback_days} days.")

        # Calculate the timestamp for the lookback period
        # Timestamps in DB are UTC epoch seconds, ensure comparison is also epoch
        start_timestamp_utc_epoch = int((datetime.utcnow() - timedelta(days=lookback_days)).timestamp())


        query_parts = [
            """
            SELECT
                r.recommendation_id, r.symbol, r.issuance_timestamp_utc, r.strategy_type,
                r.direction, r.conviction_score, r.market_regime_at_issuance,
                r.triggering_signals_json, r.ticker_context_at_issuance_json,
                o.profit_loss_absolute, o.exit_reason, o.entry_timestamp_utc AS outcome_entry_ts,
                o.exit_timestamp_utc AS outcome_exit_ts, o.actual_entry_price, o.actual_exit_price
            FROM
                Trade_Recommendations_Log r
            JOIN
                Trade_Outcomes_Log o ON r.recommendation_id = o.recommendation_id
            WHERE
                r.symbol = %s AND r.issuance_timestamp_utc >= %s
            """
        ]
        params: List[Any] = [symbol, start_timestamp_utc_epoch]

        # Add SQL parts for filters that can be easily done in SQL
        if regime_filters:
            query_parts.append("AND r.market_regime_at_issuance = ANY(%s)")
            params.append(regime_filters)
        if strategy_type_filters:
            query_parts.append("AND r.strategy_type = ANY(%s)")
            params.append(strategy_type_filters)
        
        final_query = " ".join(query_parts) + " ORDER BY r.issuance_timestamp_utc DESC;"
        
        records = self._execute_query(final_query, tuple(params), fetch_all=True)
        
        if not records:
            perf_logger.info(f"No historical trades found for {symbol} matching initial SQL criteria.")
            return pd.DataFrame()

        df = pd.DataFrame(records)
        perf_logger.info(f"Retrieved {len(df)} raw historical trades for {symbol} for performance analysis.")

        # --- Post-SQL Filtering for JSON fields (signal_filters, context_filters) ---
        if signal_filters:
            df['parsed_signals'] = df['triggering_signals_json'].apply(self._safe_json_load, default_val=[])
            for s_filter in signal_filters:
                key_path = s_filter.get("key_path", "").split('.') # e.g., "0.type" for first signal's type
                value_to_match = s_filter.get("value")
                # Basic filtering: assumes key_path refers to a primary signal type or a specific key in first signal
                if len(key_path) == 1 and key_path[0] == "type": # Simplified: filter by type of first signal
                     df = df[df['parsed_signals'].apply(lambda sig_list: any(isinstance(s, dict) and s.get('type') == value_to_match for s in sig_list if isinstance(sig_list, list)))]
                # Add more sophisticated key_path parsing if needed
            df.drop(columns=['parsed_signals'], inplace=True, errors='ignore')
            perf_logger.info(f"{len(df)} trades remaining after signal filters.")


        if context_filters:
            df['parsed_context'] = df['ticker_context_at_issuance_json'].apply(self._safe_json_load, default_val={})
            for c_filter in context_filters:
                key = c_filter.get("key_path") # Assuming simple key for now, not nested path
                value_to_match = c_filter.get("value")
                if key:
                    df = df[df['parsed_context'].apply(lambda ctx: isinstance(ctx, dict) and ctx.get(key) == value_to_match)]
            df.drop(columns=['parsed_context'], inplace=True, errors='ignore')
            perf_logger.info(f"{len(df)} trades remaining after context filters.")


        if df.empty:
            perf_logger.info(f"No trades remaining after all filters for {symbol}.")
            return pd.DataFrame()

        # --- Calculate Performance Metrics ---
        if 'profit_loss_absolute' in df.columns and pd.api.types.is_numeric_dtype(df['profit_loss_absolute']):
            df['is_win'] = df['profit_loss_absolute'] > 0
            df['is_loss'] = df['profit_loss_absolute'] < 0
            df['is_breakeven'] = df['profit_loss_absolute'] == 0
        else:
            perf_logger.warning("profit_loss_absolute column missing or not numeric. Cannot calculate win/loss stats.")
            df['is_win'] = False
            df['is_loss'] = False
            df['is_breakeven'] = True
            df['profit_loss_absolute'] = 0.0 # Ensure column exists for agg

        # Define "Setup Signature" - This is crucial for grouping.
        # Example: Primary Signal Type + Market Regime + Key Ticker Context (e.g., 0DTE)
        # This needs to be carefully designed based on how ATIF learns.
        df['primary_signal_type'] = df['triggering_signals_json'].apply(self._extract_primary_signal_type)
        df['setup_signature'] = df['primary_signal_type'].fillna('UnknownSignal') + "_" + \
                                df['market_regime_at_issuance'].fillna('UnknownRegime')
        # Could add more context to signature, e.g., from ticker_context_at_issuance_json

        performance_summary = df.groupby('setup_signature').agg(
            trade_count=('recommendation_id', 'count'),
            win_count=('is_win', 'sum'),
            loss_count=('is_loss', 'sum'),
            breakeven_count=('is_breakeven', 'sum'),
            avg_pnl=('profit_loss_absolute', 'mean'),
            total_pnl=('profit_loss_absolute', 'sum'),
            median_pnl=('profit_loss_absolute', 'median'),
            std_dev_pnl=('profit_loss_absolute', 'std'),
            # Add more stats as needed: avg_conviction, avg_duration, etc.
        ).reset_index()

        performance_summary['win_rate'] = performance_summary['win_count'] / performance_summary['trade_count']
        performance_summary['profit_factor'] = performance_summary.apply(
            lambda row: abs(row['total_pnl'] / df[df['setup_signature'] == row['setup_signature']]['profit_loss_absolute'][df['profit_loss_absolute'] < 0].sum()) 
            if df[df['setup_signature'] == row['setup_signature']]['profit_loss_absolute'][df['profit_loss_absolute'] < 0].sum() != 0 else float('inf'),
            axis=1
        )
        
        performance_summary = performance_summary[performance_summary['trade_count'] >= min_trades_for_stats].sort_values(by='win_rate', ascending=False)
        
        perf_logger.info(f"Generated performance summary for {len(performance_summary)} setups for {symbol} (min {min_trades_for_stats} trades).")
        return performance_summary


if __name__ == '__main__':
    test_logger_pt = logging.getLogger("PerformanceTracker_Standalone_Test")
    test_logger_pt.setLevel(logging.DEBUG) # Changed to DEBUG for more verbose test output
    handler_pt = logging.StreamHandler()
    formatter_pt = logging.Formatter('[%(levelname)s] (%(name)s:%(lineno)d) %(asctime)s - %(message)s')
    handler_pt.setFormatter(formatter_pt)
    if not test_logger_pt.hasHandlers():
        test_logger_pt.addHandler(handler_pt)
    
    # Configure logger for the PerformanceTrackerV2_5 class itself
    class_internal_logger = logging.getLogger(__name__) # This is the logger used by PerformanceTrackerV2_5 methods
    class_internal_logger.setLevel(logging.DEBUG)
    if not class_internal_logger.hasHandlers():
        class_internal_logger.addHandler(handler_pt)


    test_logger_pt.info("Running PerformanceTrackerV2_5 standalone example...")

    # Ensure environment variables are loaded (e.g., using dotenv or set manually)
    # For example, you might use:
    # from dotenv import load_dotenv
    # load_dotenv()

    db_host = os.environ.get("SUPABASE_DB_HOST_EOTS")
    db_name = os.environ.get("SUPABASE_DB_NAME_EOTS", "postgres")
    db_user = os.environ.get("SUPABASE_DB_USER_EOTS", "postgres")
    db_password = os.environ.get("SUPABASE_DB_PASSWORD_EOTS")
    db_port = os.environ.get("SUPABASE_DB_PORT_EOTS", "5432")

    if not db_password:
        test_logger_pt.critical("CRITICAL: SUPABASE_DB_PASSWORD_EOTS environment variable not set. Cannot run test.")
    else:
        db_connection_details_pt = {
            "host": db_host, "dbname": db_name, "user": db_user,
            "password": db_password, "port": db_port
        }
        pt = PerformanceTrackerV2_5(db_connection_details_pt)

        # 1. Test Logging a Recommendation
        test_logger_pt.info("\n--- Testing Recommendation Logging ---")
        rec_id_test = f"ATIF_PYTEST_{int(datetime.now().timestamp())}"
        sample_recommendation = {
            "recommendation_id": rec_id_test,
            "symbol": "TESTSYM_PERF",
            "issuance_timestamp_utc": int(datetime.utcnow().timestamp()), # Use UTC now
            "strategy_type": "LongCall", # Simpler strategy type
            "direction": "Bullish",
            "entry_price_ideal": 150.50,
            "stop_loss_initial": 148.00,
            "target_1_initial": 155.00,
            "target_2_initial": 160.00,
            "target_3_initial": None,
            "conviction_score": 3.8, # Float score
            "conviction_stars": 4,   # Integer stars
            "market_regime_at_issuance": "REGIME_TEST_BULLISH_FLOW",
            "ticker_context_at_issuance_json": {"is_earnings_week": False, "liquidity_profile": "High", "days_to_expiry_0dte": False}, # JSON as dict
            "triggering_signals_json": [{"type": "MSPI_Bull_Test", "score": 0.85, "strike": 150}], # JSON as list of dicts
            "atif_situational_assessment_json": {"flow_score": 0.75, "structure_score": 0.65, "vol_score": 0.5}, # JSON as dict
            "current_status": "ACTIVE_NEW",
            "selected_contracts_json": [{"optionSymbol": "TESTSYM_C_150", "action": "BUY", "ratio": 1}], # JSON as list of dicts
            "parameters_detail_json": {"atr_at_signal": 2.55, "target_method": "ATR_MULT"} # JSON as dict
        }
        logged_rec_id = pt.log_atif_recommendation(sample_recommendation)
        if logged_rec_id:
            test_logger_pt.info(f"Recommendation logged successfully: ID {logged_rec_id}")
        else:
            test_logger_pt.error("Failed to log recommendation.")

        # 2. Test Logging a Trade Outcome
        test_logger_pt.info("\n--- Testing Trade Outcome Logging ---")
        if logged_rec_id: 
            sample_outcome = {
                "recommendation_id": logged_rec_id,
                "symbol": "TESTSYM_PERF", 
                "entry_timestamp_utc": int((datetime.utcnow() - timedelta(hours=1)).timestamp()),
                "actual_entry_price": 150.75,
                "contracts_traded_json": [{"optionSymbol": "TESTSYM_C_150", "action": "BUY", "qty":1, "fill_price":150.75}],
                "exit_timestamp_utc": int(datetime.utcnow().timestamp()),
                "actual_exit_price": 155.25,
                "exit_reason": "Target1_Hit_System",
                "profit_loss_absolute": (155.25 - 150.75) * 100, 
                "profit_loss_percentage": ((155.25 - 150.75) / 150.75) * 100 if 150.75 else 0,
                "metrics_at_entry_json": {"mspi": 0.7, "vapi_fa": 1.2},
                "metrics_at_exit_json": {"mspi": 0.5, "vapi_fa": -0.3},
                "notes_json": {"comment": "Exited at T1 automatically by system logic"}
            }
            logged_outcome_id = pt.log_trade_outcome(sample_outcome)
            if logged_outcome_id is not None: 
                test_logger_pt.info(f"Trade outcome logged successfully. Trade Log ID: {logged_outcome_id}")
            else:
                test_logger_pt.error("Failed to log trade outcome.")
        else:
            test_logger_pt.warning("Skipping outcome logging as recommendation logging failed.")

        # 3. Test Retrieving Historical Performance
        test_logger_pt.info("\n--- Testing Historical Performance Retrieval ---")
        perf_df = pt.get_historical_performance_for_setups(
            symbol="TESTSYM_PERF",
            lookback_days=7,
            min_trades_for_stats=1, 
            regime_filters=["REGIME_TEST_BULLISH_FLOW"],
            signal_filters=[{"key_path": "type", "value": "MSPI_Bull_Test"}] # Test basic signal filter
        )
        if not perf_df.empty:
            test_logger_pt.info(f"Retrieved performance data for TESTSYM_PERF:\n{perf_df.to_string()}")
        else:
            test_logger_pt.warning("No performance data retrieved for TESTSYM_PERF with current filters.")

        test_logger_pt.info("PerformanceTrackerV2_5 standalone example finished.")

